model_list:

  - model_name: gpt-5
    litellm_params:
      model: gpt-5-nano-2025-08-07
      api_key: "os.environ/OPENAI_API_KEY"
      api_base: https://api.openai.com/v1

  - model_name: claude-4
    litellm_params:
      model: claude-opus-4-5-20251101
      api_key: "os.environ/ANTHROPIC_API_KEY"
      base_url: 'https://api.anthropic.com'

  - model_name: gemini-3
    litellm_params:
      model: gemini/gemini-3-flash-preview
      api_key: "os.environ/GEMINI_API_KEY"

  # f√∂r skojs skull
  - model_name: mistral:7b
    litellm_params:
      model: ollama/mistral:7b
      api_base: http://localhost:11434  # Default Ollama port
      api_key: "dummy" # Ollama doesn't need a real API key

litellm_settings:
  drop_params: true
  set_verbose: true

general_settings:
  database_url: null
  store_model_in_db: false

